### ISSUE TITLE
Only generate one empty monitor file in my own fuzzer

### ISSUE THREAD

**Issue by qhjchc** [HexHive/magma#110]
Hi, there

I try to run my own fuzzer in the magma, all the configurations are copied from the AFL.

However, the monitor files of my own fuzzer could not be collected by magma. 
There is only one file `5` in the monitor folder, but the files in `findings` shows that the fuzzer is running successfully with some crashes. Other fuzzers such AFL could generate monitor files successfully with a similar configuration.

What else I should pay attention to when setting up our own fuzzers?

**Comment by adrianherrera** [comment]
Do you have a public repo I could take a look at?

**Comment by qhjchc** [comment]
Sorry, the fuzzer is not published yet. I could provide the log if necessary.

The following are the modified configuration of my own fuzzer. 
- build.sh
   `make -j $(nproc)`
   `CC=clang make -j $(nproc) -C llvm_mode`
- instrument.sh
   `export CFLAGS="-res=$OUT"`
- preinstall. sh
   install glib2.29

Is there any recommended method for users to debug it in the docker?
