### ISSUE TITLE
Small Typo in afl_asan, cause image build failed

### ISSUE THREAD

**Issue by kdsjZh** [HexHive/magma#111]
Hello Ahmad, I'm testing my fuzzer with afl_asan and find it fail to build, which is because a small typo.

https://github.com/HexHive/magma/blob/a8e440b8f976530345c92451b75809985775fb41/fuzzers/afl_asan/fetch.sh#L10. 

```git -C $"FUZZER/repo"``` should be change to ```git -C "$FUZZER/repo" ```. 

Could you fix it when you're available?  Thanks.

**Comment by adrianherrera** [comment]
Fixed in the dev branch!
