### ISSUE TITLE
Crash reproduction problem (running aflplusplus-libtiff)

### ISSUE THREAD

**Issue by mengnanpeter** [HexHive/magma#112]
Hello guys, I'm trying to do some fuzzing jobs on this benchmark, but there is something that makes me quite confused.

Here is the thing: I built and ran the aflplusplus-libtiff image (which tests two bins, tiff_cp and tiff_read_rgba_fuzzer, using aflplusplus) as the website says, and some crashes showed up in "****/findings/default/crashes" dic after 24-hour running. From what I understand, the files in that dic can trigger the crash when used as input to the corresponding bin, i, e, crash can be reproduced by these files.

But it makes me very confused that nothing but "Execution successfully" came up when I feed crash files into tiff_read_rgba_fuzzer. I can make sure that the memory limitation is not the reason, and the environment configs should be all right because I did the test both in the host machine and docker container (which is used to do the fuzzing and produce the crashes).

So, does anybody know why this is happening? Any help will be much appreciated.

Parts of the run log:
[*] Fuzzing test case #4737 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=229, hits=312286, map=272)...
[*] Fuzzing test case #642 (5492 total, 317 uniq crashes found, perf_score=257, exec_us=268, hits=5477, map=342)...
[*] Fuzzing test case #1802 (5492 total, 317 uniq crashes found, perf_score=515, exec_us=255, hits=22, map=293)...
[*] Fuzzing test case #5458 (5492 total, 317 uniq crashes found, perf_score=862, exec_us=269, hits=7503, map=398)...
[*] Fuzzing test case #4702 (5492 total, 317 uniq crashes found, perf_score=690, exec_us=287, hits=2248, map=635)...
[*] Fuzzing test case #3557 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=294, hits=6895, map=473)...
[*] Fuzzing test case #4321 (5492 total, 317 uniq crashes found, perf_score=459, exec_us=296, hits=66159, map=669)...
[*] Fuzzing test case #4610 (5492 total, 317 uniq crashes found, perf_score=690, exec_us=280, hits=72, map=601)...
[*] Fuzzing test case #1425 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=263, hits=3833, map=512)...
[*] Fuzzing test case #393 (5492 total, 317 uniq crashes found, perf_score=172, exec_us=252, hits=41, map=402)...
[*] Fuzzing test case #3149 (5492 total, 317 uniq crashes found, perf_score=459, exec_us=311, hits=75489, map=590)...
[*] Fuzzing test case #2704 (5492 total, 317 uniq crashes found, perf_score=127, exec_us=219, hits=1406901, map=138)...
[*] Fuzzing test case #3149 (5492 total, 317 uniq crashes found, perf_score=459, exec_us=311, hits=75581, map=590)...
[*] Fuzzing test case #3766 (5492 total, 317 uniq crashes found, perf_score=459, exec_us=299, hits=114987, map=690)...
[*] Fuzzing test case #2109 (5492 total, 317 uniq crashes found, perf_score=517, exec_us=278, hits=106, map=442)...
[*] Fuzzing test case #5445 (5492 total, 317 uniq crashes found, perf_score=862, exec_us=269, hits=5899, map=400)...
[*] Fuzzing test case #1812 (5492 total, 317 uniq crashes found, perf_score=180, exec_us=286, hits=296, map=488)...
[*] Fuzzing test case #5117 (5492 total, 317 uniq crashes found, perf_score=1035, exec_us=291, hits=11, map=580)...
[*] Fuzzing test case #4272 (5492 total, 317 uniq crashes found, perf_score=517, exec_us=276, hits=121212, map=577)...
[*] Fuzzing test case #4113 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=282, hits=7125, map=421)...
[*] Fuzzing test case #3296 (5492 total, 317 uniq crashes found, perf_score=517, exec_us=261, hits=181227, map=444)...
[*] Fuzzing test case #5458 (5492 total, 317 uniq crashes found, perf_score=862, exec_us=269, hits=7559, map=398)...
[*] Fuzzing test case #2910 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=265, hits=14923, map=537)...
[*] Fuzzing test case #1631 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=274, hits=3541, map=573)...
[*] Fuzzing test case #2227 (5492 total, 317 uniq crashes found, perf_score=690, exec_us=280, hits=93627, map=478)...
[*] Fuzzing test case #4419 (5492 total, 317 uniq crashes found, perf_score=160, exec_us=291, hits=97, map=606)...
[*] Fuzzing test case #3097 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=263, hits=35229, map=393)...
[*] Fuzzing test case #2062 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=314, hits=6631, map=624)...
[*] Fuzzing test case #2481 (5492 total, 317 uniq crashes found, perf_score=517, exec_us=281, hits=14083, map=429)...
[*] Fuzzing test case #346 (5492 total, 317 uniq crashes found, perf_score=172, exec_us=273, hits=1918, map=385)...
[*] Fuzzing test case #4331 (5492 total, 317 uniq crashes found, perf_score=459, exec_us=293, hits=82452, map=653)...
[*] Fuzzing test case #4797 (5492 total, 317 uniq crashes found, perf_score=690, exec_us=261, hits=119984, map=438)...
[*] Fuzzing test case #2668 (5492 total, 317 uniq crashes found, perf_score=517, exec_us=266, hits=10380, map=580)...
[*] Fuzzing test case #2668 (5492 total, 317 uniq crashes found, perf_score=517, exec_us=266, hits=10439, map=580)...
[*] Fuzzing test case #4737 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=229, hits=312406, map=272)...
[*] Fuzzing test case #2251 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=279, hits=2314, map=622)...
[*] Fuzzing test case #3459 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=276, hits=69, map=403)...
[*] Fuzzing test case #5321 (5492 total, 317 uniq crashes found, perf_score=690, exec_us=269, hits=32966, map=523)...
[*] Fuzzing test case #4321 (5492 total, 317 uniq crashes found, perf_score=459, exec_us=296, hits=66208, map=669)...
[*] Fuzzing test case #4797 (5492 total, 317 uniq crashes found, perf_score=690, exec_us=261, hits=120058, map=438)...
[*] Fuzzing test case #4777 (5492 total, 317 uniq crashes found, perf_score=459, exec_us=299, hits=82, map=424)...
[*] Fuzzing test case #3888 (5492 total, 317 uniq crashes found, perf_score=345, exec_us=293, hits=2924, map=458)...
[*] Fuzzing test case #2481 (5492 total, 317 uniq crashes found, perf_score=517, exec_us=281, hits=14200, map=429)...
[*] Fuzzing test case #5321 (5492 total, 317 uniq crashes found, perf_score=690, exec_us=269, hits=33044, map=523)...
[*] Fuzzing test case #2970 (5492 total, 317 uniq crashes found, perf_score=690, exec_us=283, hits=57654, map=533)...
[*] Fuzzing test case #4096 (5492 total, 317 uniq crashes found, perf_score=459, exec_us=297, hits=35930, map=507)...
[*] Fuzzing test case #5420 (5492 total, 317 uniq crashes found, perf_score=575, exec_us=302, hits=11531, map=404)...
[*] Fuzzing test case #2486 (5492 total, 317 uniq crashes found, perf_score=517, exec_us=284, hits=36, map=395)...
[*] Fuzzing test case #2855 (5492 total, 317 uniq crashes found, perf_score=257, exec_us=260, hits=29539, map=354)...
[*] Fuzzing test case #1635 (5492 total, 317 uniq crashes found, perf_score=300, exec_us=302, hits=49, map=687)...

"Execution successful." Info when try to reproduce the crash in container
magma@641e62791f94:/magma_out/afl$ ./tiff_read_rgba_fuzzer /crashes/id\:000003\,sig\:11\,src\:000410\,time\:38176\,op\:havoc\,rep\:4 
Reading 384 bytes from /crashes/id:000003,sig:11,src:000410,time:38176,op:havoc,rep:4
Monitor not running. Canaries will be disabled.
Execution successful.

**Comment by adrianherrera** [comment]
Not sure about those crashes, but you don't need to look at them. Instead, uou need to look at what the monitor produces, per https://hexhive.epfl.ch/magma/docs/getting-started.html

**Comment by mengnanpeter** [comment]
Many thanks for your reply. I understand what the monitor produces, just being confused when the file in findings cannot reproduce the crash. I am going to analyze the crash-related information, so these files really matter in my experiments.

When I used honggfuzz instead of aflplusplus, the same thing happened even with the log files indicating that the crash was found by the file. It does not make sense and I just can't figure it out.

Parts of the honggfuzz log:
FUZZER ARGS:
 mutationsPerRun : 5
 externalCmd     : NULL
 fuzzStdin       : TRUE
 timeout         : 1 (sec)
 ignoreAddr      : (nil)
 ASLimit         : 0 (MiB)
 RSSLimit        : 0 (MiB)
 DATALimit       : 0 (MiB)
 wordlistFile    : NULL
 dynFileMethod   : 
 fuzzTarget      : /magma_out/tiff_read_rgba_fuzzer 
CRASH:
DESCRIPTION: 
ORIG_FNAME: 429620cd48837ca2b9a5b41cb4386658.000002ed.honggfuzz.cov
FUZZ_FNAME: /magma_shared/findings/SIGSEGV.PC.7ffff6632177.STACK.18f56afb84.CODE.0.ADDR.0.INSTR.cmp____$0xfffffffffffff001,%rax.fuzz
PID: 342
SIGNAL: SIGSEGV (11)
PC: 0x7ffff6632177
FAULT ADDRESS: 0x0
INSTRUCTION: cmp____$0xfffffffffffff001,%rax
STACK HASH: 00000018f56afb84
STACK:
 <0x000000000050aff1> [func:magma_log file:/magma/magma/src/canary.c line:95 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x000000000044e571> [func:ChopUpSingleUncompressedStrip file:/magma/targets/libtiff/repo/libtiff/tif_dirread.c line:5986 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x00000000004423fc> [func:TIFFReadDirectory file:/magma/targets/libtiff/repo/libtiff/tif_dirread.c line:4319 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x00000000004772dc> [func:TIFFClientOpen file:/magma/targets/libtiff/repo/libtiff/tif_open.c line:483 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x0000000000429629> [func:_tiffStreamOpen file:/magma/targets/libtiff/repo/libtiff/tif_stream.cxx line:378 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x0000000000429769> [func:TIFFStreamOpen file:/magma/targets/libtiff/repo/libtiff/tif_stream.cxx line:417 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x0000000000428138> [func:LLVMFuzzerTestOneInput file:/magma/targets/libtiff/repo/contrib/oss-fuzz/tiff_read_rgba_fuzzer.cc line:56 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x00000000005118ef> [func:HonggfuzzPersistentLoop file:persistent.c line:0 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x0000000000511b59> [func:main file: line:0 module:/magma_out/tiff_read_rgba_fuzzer]
 <0x00007ffff6614c87> [func:UNKNOWN file: line:0 module:/lib/x86_64-linux-gnu/libc-2.27.so]
 <0x000000000040669a> [func:_start file: line:0 module:/magma_out/tiff_read_rgba_fuzzer]

The result when running using the file SIGSEGV.PC.7ffff6632177.STACK.18f56afb84.CODE.0.ADDR.0.INSTR.cmp____$0xfffffffffffff001,%rax.fuzz in docker env:

magma@641e62791f94:/$ ./magma_out/afl/tiff_read_rgba_fuzzer /findings/SIGSEGV.PC.7ffff6632177.STACK.18f56afb84.CODE.0.ADDR.0.INSTR.cmp____\$0xfffffffffffff001\,%rax.fuzz 
Reading 965 bytes from /findings/SIGSEGV.PC.7ffff6632177.STACK.18f56afb84.CODE.0.ADDR.0.INSTR.cmp____$0xfffffffffffff001,%rax.fuzz
Monitor not running. Canaries will be disabled.
Execution successful.

also the monitor file show:
at time 85680
TIF012_R,TIF012_T,TIF003_R,TIF003_T,TIF007_R,TIF007_T,TIF014_R,TIF014_T,TIF010_R,TIF010_T,TIF002_R,TIF002_T
16895030,254,298882549,0,2115980,46405,2069575,5400,399483,0,640,0

Could anyone please enlighten me about this? Any help will be much appreciated.

**Comment by Marsman1996** [comment]
Do you compile the `magma.o` with flag `-DMAGMA_FATAL_CANARIES`?
According to the code in `magma_log`, it seems that only when the `MAGMA_FATAL_CANARIES` is defined, the signal will be sent.

https://github.com/HexHive/magma/blob/75d1ae7b180443a778b8830c79176ca5f93642ac/magma/src/canary.c#L86-L93
