### ISSUE TITLE
Building the docker container fails

### ISSUE THREAD

**Issue by jleni** [HexHive/magma#12]
Instructions seem to be incorrect. 
At the moment, it is not possible to build the container and there are some issues such as trying to copy from a parent path. Something that docker does not allow.

**Comment by hazimeh** [comment]
Hi jleni, thank you for raising this issue.
We are aware that the build instructions on the master branch are outdated.
Please find the update instructions on the Magma homepage:
https://hexhive.epfl.ch/magma/
