### ISSUE TITLE
magma/run.sh: line 55: tmp.out: syntax error

### ISSUE THREAD

**Issue by peytonshields** [HexHive/magma#132]
Hello! When running any campaign with the latest version of Magma v1.2, I get a syntax error in run.sh in the container log that says 

```
 [2023-01-18 15:12] Container for afl/libtiff/tiffcp started in 3374cf4b0ba6
 /magma/magma/run.sh: line 55: tmp.out: syntax error: invalid arithmetic operator (error token is ".out")
 Campaign launched at 2023-01-18 20:12
 mv: '/magma_shared/monitor/tmp' and '/magma_shared/monitor/tmp' are the same file
```

Relevant line number in magma/run.sh shown below.

```bash
  47 # launch the fuzzer in parallel with the monitor
  48 rm -f "$MONITOR/tmp"*
  49 polls=("$MONITOR"/*)
  50 if [ ${#polls[@]} -eq 0 ]; then
  51     counter=0
  52 else
  53     timestamps=($(sort -n < <(basename -a "${polls[@]}")))
  54     last=${timestamps[-1]}
  55     counter=$(( last + POLL ))
  56 fi
```

After testing locally with bash, it looks like the contents of the $MONITOR directory aren't expanded when polls is assigned, meaning that line 50 always detects a non-zero size. This issue doesn't exist in zsh, which properly expands the $MONITOR directory. 

Changing line 50 to below fixes the syntax error for compatibility with various shells:

```bash
polls=($(ls ${MONITOR}))
```

**Comment by adrianherrera** [comment]
Thanks for this! Did you submit a PR?

**Comment by peytonshields** [comment]
See PR #133 

I originally closed the issue because the error only seems to occur on certain versions of bash, but might as well make the change anyway for greater compatibility
