### ISSUE TITLE
llvm-dis error

### ISSUE THREAD

**Issue by ramerzase** [HexHive/magma#135]
I initially compiled the program with wllvm and use the LLVM’s (version 11) opt tool to extract each function’s intra-procedural CFG. I successfully extracted ICFG on **lua**. But when testing **libpng**, I successfully used extract-bc to extract the bitcode corresponding to libpng16.a:

```
Writing output to $MAGMA/targets/libtiff/repo/work/lib/libtiff.bc
llvm-ar: warning: creating $MAGMA/targets/libtiff/repo/work/lib/libtiff.bc
Generated LLVM bitcode archive $MAGMA/targets/libtiff/repo/work/lib/libtiff.bc
```

but then an error occurred when using llvm-dis to convert .bc to .ll:

```
my command: llvm-dis libtiff.bc
llvm-dis: error: file doesn't start with bitcode header
```

The same problem also appears on **libxml(libxml2.a), libtiff**(**libtiffxx.a**). I would like to ask why I can successfully extract icfg on **lua** but not on programs such as **libpng** and **libtiff**(library form)?

**Comment by adrianherrera** [comment]
Hi @ramerzase ,

Can you be a bit more specific; are you doing this inside a custom fuzzer? There is an `llvm_analysis` target that uses gclang (rather than wllvm, which is older and slower) to extract whole-program bitcode. Is this what is broken?

**Comment by ramerzase** [comment]
> Hi @ramerzase ,
> 
> Can you be a bit more specific; are you doing this inside a custom fuzzer? There is an `llvm_analysis` target that uses gclang (rather than wllvm, which is older and slower) to extract whole-program bitcode. Is this what is broken?

Sorry for not being specific enough in my description. I want to experiment on the magma test set using my own fuzzer. After compiling the target program with my own compiling toolchain, I tried to extract the CFG of the target program through extract-bc, llvm-dis and other tools and merge it into ICFG. However, when testing `libpng`, after I use extract-bc to extract the bitcode of `.libs/libpng16.a`, I cannot convert `.bc` to `.ll` using llvm-dis. Based on your reply, I'll give gllvm a try. Besides that I have some questions. 
1. According to the `build.sh` in `magma/targets/libpng` folder, I still need to build the `libpng_read_fuzzer`. So should I extract the ICFG of libpng_read_fuzzer or the ICFG of libpng16.a?
2. Unlike libpng, I noticed that there are multiple subfolders under the corpus folder of `libxml` and `libtiff` (eg,. `tiff_read_rgba_fuzzer` and `tiffcp` in `magma/targets/libtiff/corpus`). So can I run xmllint directly without building `tiff_read_rgba_fuzzer` when testing `libxml`? If so, what is the difference between the two approaches?

Looking forward to your reply~

**Comment by ramerzase** [comment]
> > Hi @ramerzase ,
> > Can you be a bit more specific; are you doing this inside a custom fuzzer? There is an `llvm_analysis` target that uses gclang (rather than wllvm, which is older and slower) to extract whole-program bitcode. Is this what is broken?
> 
> Sorry for not being specific enough in my description. I want to experiment on the magma test set using my own fuzzer. After compiling the target program with my own compiling toolchain, I tried to extract the CFG of the target program through extract-bc, llvm-dis and other tools and merge it into ICFG. However, when testing `libpng`, after I use extract-bc to extract the bitcode of `.libs/libpng16.a`, I cannot convert `.bc` to `.ll` using llvm-dis. Based on your reply, I'll give gllvm a try. Besides that I have some questions.
> 
> 1. According to the `build.sh` in `magma/targets/libpng` folder, I still need to build the `libpng_read_fuzzer`. So should I extract the ICFG of libpng_read_fuzzer or the ICFG of libpng16.a?
> 2. Unlike libpng, I noticed that there are multiple subfolders under the corpus folder of `libxml` and `libtiff` (eg,. `tiff_read_rgba_fuzzer` and `tiffcp` in `magma/targets/libtiff/corpus`). So can I run xmllint directly without building `tiff_read_rgba_fuzzer` when testing `libxml`? If so, what is the difference between the two approaches?
> 
> Looking forward to your reply~

I tried to use gllvm instead of wllvm, but still encountered the same error when using llvm-dis:

```
my command: get-bc -o libpng16.a.bc libpng16.a
> llvm-ar: warning: creating /data/data2/zhangfw_lab/cse30017189/fuzz/testcases/magma/targets/libpng/repo/libpng16.a.bc
> Built bitcode archive: libpng16.a.bc.
my command: llvm-dis libpng16.a.bc
> llvm-dis: error: Invalid bitcode signature
```

**Comment by adrianherrera** [comment]
Oh right, yes, sorry, I know what the issue is.

When you run `get-bc` you need to provide the `-b` when running over a static library. If you run `file` over `libpng16.a.bc` you'll find that it is indeed not a bitcode file, but rather a library of bitcode files.

This is not a Magma issue.
