### ISSUE TITLE
Error running AFL

### ISSUE THREAD

**Issue by fang-siqi** [HexHive/magma#138]
When I try to run AFL to fuzz the libxml2 library, the `echo core>/proc/sys/kernel/core`  error prompt message appears. Which. sh file should I add to fix this error?Or how should I set it up?

**Comment by adrianherrera** [comment]
None. You need to do this on your native system.

**Comment by fang-siqi** [comment]
Ok, is there a guide for building the MAGMA data set locally outside the docker?

**Comment by adrianherrera** [comment]
Sorry, I don't understand. Magam is designed to build and run everything inside Docker container (much like FuzzBench). Why do you want to build & run AFL on libxml2 outside of Docker? Just run

```
echo core>/proc/sys/kernel/core
```

As root on your machine and then run the Magma process again.
