### ISSUE TITLE
K-Scheduler fails to compile lua

### ISSUE THREAD

**Issue by ramerzase** [HexHive/magma#139]
I successfully compiled K-Scheduler and used K-Scheduler's compilation toolchain to successfully compile libpng and sndfile in magma benchmark, but failed when compiling lua (I refer to the scripts in the magma/fuzzers/K-Scheduler folder and magma/targets/*/build.sh). The error is as follows:
```
undefined reference to `__sanitizer_cov_trace_const_cmp4'
undefined reference to `__asan_report_load4'
undefined reference to `__sanitizer_cov_trace_const_cmp4'
undefined reference to `__asan_report_load8'
```
These errors seem to be caused by coverage-sanitizer, but I don't know why I don't encounter this problem with libpng and libsndfile.
Wondering if anyone has had a similar problem?

**Comment by adrianherrera** [comment]
Weird, I don't get that error. I run

```
TARGET=lua FUZZER=k_scheduler ./tools/captain/build.sh
```

and it works fine.

Can you please provide your build command and the output error trace?

**Comment by ramerzase** [comment]
> Weird, I don't get that error. I run
> 
> ```
> TARGET=lua FUZZER=k_scheduler ./tools/captain/build.sh
> ```
> 
> and it works fine.
> 
> Can you please provide your build command and the output error trace?

Thanks for your reply. My build command is as follows:
```
# set K-Scheduler env
export LLVM_COMPILER=clang 
export CC=wllvm
export CXX=wllvm++
export CFLAGS="-fsanitize-coverage=trace-pc-guard,no-prune -O2 -fno-omit-frame-pointer -gline-tables-only -fsanitize=address,fuzzer-no-link -fsanitize-address-use-after-scope"
export CXXFLAGS="-fsanitize-coverage=trace-pc-guard,no-prune -O2 -fno-omit-frame-pointer -gline-tables-only -fsanitize=address,fuzzer-no-link -fsanitize-address-use-after-scope"
export LDFLAGS=$K-Scheduler/afl-llvm-rt.o

# enter lua repo
cd $TAGET/repo
make -j$(nproc) clean
make -j$(nproc) liblua.a
cp liblua.a "$OUT/"
make -j$(nproc) lua
```
I built `liblua.a` successfully and the error occurs when I execute `make -j$(nproc) lua`. I put the output error trace in the [a.log](https://github.com/HexHive/magma/files/11099729/a.log).
Thank you very much.

**Comment by adrianherrera** [comment]
Thanks for that.

Is there any particular reason you are not using the provided scripts? Is there a reason you've enabled sanitise-coverage? Unless you are using the magma build process, your question may be better directed at the k-scheduler devs.

**Comment by ramerzase** [comment]
> sanitise-coverage

Thank you for your reply.
1. In fact, I am deploying magma outside docker according to this [issue](https://github.com/HexHive/magma/issues/93). Therefore, I refer to the build.sh that comes with magma and the issue in the repo of k-scheduler to compile lua with the toolchain of k-scheduler.
2. The reason for enabling sanitise-coverage is that k-scheduler uses sanitise-coverage for instrumentation.
3. *There is another problem*. I used AFL and AFLFast to fuzz `sqlite3` and `lua`, but both of AFL and AFLFast couldn't find the crash within 24 hours. Should I add a [dictionary](https://github.com/google/fuzzing/tree/master/dictionaries) when fuzzing some programs in magma?

**Comment by adrianherrera** [comment]
Ok thanks for the clarification. There's not much I can do about 1, because this is outside of Magma's scope and not supported .

With respect to 3, what specific crash are you referring to? Do you mean it didn't trigger _any_ bugs? I would compare your results to the magma website. Given the fuzzers and campaign lengths are similar, it should be a similar result.

**Comment by ramerzase** [comment]
> Ok thanks for the clarification. There's not much I can do about 1, because this is outside of Magma's scope and not supported .
> 
> With respect to 3, what specific crash are you referring to? Do you mean it didn't trigger _any_ bugs? I would compare your results to the magma website. Given the fuzzers and campaign lengths are similar, it should be a similar result.

Yes, I built the target programs(`sqlite3` and `lua`) on my own server, the AFLFast and AFL failed to find crashes during 24 hours of fuzzing.

**Comment by adrianherrera** [comment]
Hi @ramerzase, I'm going to close this now. If you have further questions about AFLFast/AFL, please open a new issue.
