### ISSUE TITLE
Does a Bug ID to CVE ID mapping exist for the libtiff target?

### ISSUE THREAD

**Issue by DanielEbert** [HexHive/magma#14]
Hello I am interested in the CVE ID for each BUG ID in the libtiff target. The files for libtiff are missing or do not exist in the magma/docs/Buggy_MDs folder from pull request #11 .
Does a Bug ID to CVE ID mapping exist for the libtiff target?

**Comment by cjordan7** [comment]
Hello,

Yes, it does exist. I just forgot to add it. 

Now it is done.

**Comment by DanielEbert** [comment]
Thank you :)

**Comment by hazimeh** [comment]
I have also added a page summarizing those mappings to the Magma website:
https://hexhive.epfl.ch/magma/docs/bugs.html
