### ISSUE TITLE
How do you use `llvm_cov` and `llvm_analysis`?

### ISSUE THREAD

**Issue by acidghost** [HexHive/magma#144]
As I understand `llvm_analysis` is meant to be copied / extended to implement our own analysis on the targets.

But I have no clue on how to use `llvm_cov`.

Also, what if I have an analysis / instrumentation that needs to execute the target over a corpus produced by a fuzzer?

**Comment by adrianherrera** [comment]
Good questions! Yeah, these aren't really documented anywhere. TBH they're not really part of the Magma benchmark per-se. `llvm_analysis` is useful if you want to extract and analyze the LLVM IR of the Magma targets, which `llvm_cov` is useful if you want to replay fuzzer queues post running a Magma campaign.

There is no automation to do this automatically; although if you do something useful with them we'd happily consider a PR!
