### ISSUE TITLE
Which bugs are reachable and trigger-able

### ISSUE THREAD

**Issue by acidghost** [HexHive/magma#147]
I see from the paper that not all bugs included in `targets/*/patches/bugs/` are actually trigger-able. Is this correct? If so, why are they not in the graveyard?

Do you keep a list of the bugs that can be triggered (i.e. have Proof of Vulnerability)? Especially given that some targets (`lua` and `libsndfile`) have been added after the paper's publication.

**Comment by adrianherrera** [comment]
Hi Andrea,

Just because _we_ didn't trigger them, doesn't make them untriggerable. Hence why they are not in the graveyard.

PoCs for triggerable bugs in the original paper are available at https://osf.io/resj8/ Unfortunately we do not have an updated list of triggered bugs. However, looking at papers that use Magma in their evaluation should give you a reasonable idea.

**Comment by acidghost** [comment]
I'm sorry, but I do not understand the meaning of this quote from the paper then:

> When available, we extract PoVs from public bug reports. When no PoV is available, we launch multiple fuzzing campaigns against these targets in an attempt to trigger each injected bug. Inputs that trigger a bug are saved as a PoV. **Bugs which are not triggered, even after multiple campaigns, are manually inspected to verify path reachability and satisfiability of trigger conditions**.

As far as I understand it, if bugs were not triggered by the fuzzing campaigns you manually inspected them to verify reachability and triggerability. Is this correct?

What is the meaning of the green checkmark on the PoV column in the tables from the paper?

**Comment by acidghost** [comment]
Additionally:
> In total, during the 24 h campaigns, 74 of the 118 Magma bugs (62 %) were reached. Additionally, 43 of the 54 verified bugs (79 %)—i.e., those with PoVs—were triggered.

Verified bugs are those with PoV. Are the remaining ones unverified then?

**Comment by adrianherrera** [comment]
>As far as I understand it, if bugs were not triggered by the fuzzing campaigns you manually inspected them to verify reachability and triggerability. Is this correct?

Good Q; I'll have to leave that with @hazimeh to answer.

>What is the meaning of the green checkmark on the PoV column in the tables from the paper?

It means it should be available in the link I provided earlier.
