### ISSUE TITLE
Want the object files for reversing

### ISSUE THREAD

**Issue by anzosasuke** [HexHive/magma#148]
I would like to use all these binaries for different purpose. For that I would like to get the object files of libraries. How do you suggest I do that?
First is using a virtual machine and install these vulnerable libraries and get it. I was hoping if you have something in this repository that could help me. 
Thanks in advance.

**Comment by adrianherrera** [comment]
Hi there,

You don't need a full-blown VM. Everything in Magma is Docker container-based, so once you've built the containers you can just run them in interactive mode and copy out the compiled binaries.

Just a comment: the binaries are probably not particularly interesting to RE from a vulnerability research/analysis perspective. The bugs are very easy to spot; just calls to the Magma logging functions.
