### ISSUE TITLE
Empty ARGS with non-empty seed corpus for fuzzing targets

### ISSUE THREAD

**Issue by choonginlee** [HexHive/magma#154]
Hi,
Thank you for the endeavor to provide a great benchmark.

I am running various types of fuzzers on Magma, and I am curious about empty `$ARGS` parameters in certain fuzzing targets. 
For example, **/magma/targets/libpng/configrc** shows `PROGRAMS=(libpng_read_fuzzer)` where there is no argument for the `libpng_read_fuzzer`.
However, I can see several .png files in the libpng input corpus **/magma/targets/libpng/corpus/libpng_read_fuzzer**, which are processed in `runonce.sh` as far as I understand.
I can see some other fuzzing targets in Magma are carried with AFL-style arguments containing `@@` for the input location, which is easy to understand.
Could you explain how the empty-`$ARGS` targets such as `libpng_read_fuzzer` process input corpus? 
Do they not use seed files in the input corpus?

Is the case the same as the paper (https://hexhive.epfl.ch/publications/files/21ISSTA2.pdf) mentioned as _empty_ seed?

Thank you for the answer in advance.

**Comment by adrianherrera** [comment]
Hi @choonginlee 

This is related to the AFL++ driver and where it gets it's arguments from. See here for the source: https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/aflpp_driver/aflpp_driver.c

At a high level (and very generalised): if the target provides a libfuzzer-style harness (like libpng), then the AFL++ driver is used and you don't need @@. Other targets (like xmllint) provide their own driver, and so you need to use @@.

IIRC there is no empty seed use in magma. Seed corpora are provided and used for all targets.

Hope that helps!
