### ISSUE TITLE
Patching errors for poppler, php, libxml2, openssl

### ISSUE THREAD

**Issue by benjaminor** [HexHive/magma#25]
Running fuzzers for these targets fails due to patching errors:
- poppler: AAH042
- php: MAE006
- libxml2: AAH036
- openssl: MAE110

I saw that for the targets you clone the master branch and apply the patches on this branch, maybe you could pin the cloning to a specific commit where you know the patches will succeed?

**Comment by hazimeh** [comment]
Consider checking out the `v1.0` branch, where targets and fuzzers are anchored to specific refs.
