### ISSUE TITLE
Unexpected _TARGETS behavior

### ISSUE THREAD

**Issue by anaaktge** [HexHive/magma#28]
Magma is really nifty and I'm plan to use it for my quals research on initial corpus impact. 

Initially I wanted to just study seed behavior on one specific target (libxml2) and run all the fuzzers against it.
 
captainrc on line ~76 says
```
# [fuzzer_TARGETS]: an array of target names (from magma/targets/*) to fuzz with
# `fuzzer` (default: all targets)
# afl_TARGETS=(libpng libtiff libxml2)
```

So I ran with 
```
# FUZZERS: an array of fuzzer names (from magma/fuzzers/*) to evaluate
FUZZERS=(afl aflfast)

# [fuzzer_TARGETS]: an array of target names (from magma/targets/*) to fuzz with
# `fuzzer` (default: all targets)
afl_TARGETS=(libxml2)
```
AFL ran just on libxml2 as expected, aflfast ran on all targets. I had noticed the name of the variable in the comment was paired to afl, however it's not uncommon for configuration variables to have outdated names or historical artifact names.
 
Based on https://github.com/HexHive/magma/issues/24#issuecomment-688395943 it sounds like the documentation is misleading. Perhaps the best fix is update the comments with more information. Where exactly is the fuzzer prefix derived from? Is it the directory name of the target? That would be a really handy thing to put in the documentation. I see you've added quite a few fuzzers since I first installed magma, so a static list probably isn't the best idea. 

Thanks!

Unrelated to that, what is the best way to get in contact or stay abreast of new magma's plans? Issues? email? slack?

**Comment by adrianherrera** [comment]
Hey there Allison,

You are correct, the fuzzer prefix is derived from the directory names in `fuzzers/`. I agree, an update to the comment is the way to go (as you said, new fuzzers have been added since the project was first started).

Hmm good question re. staying abreast of Magma plans. No plans at the moment, however there is an "Awesome Fuzzing" discord where we hang out and people discuss Magma (and other benchmarks).

**Comment by hazimeh** [comment]
I think Adrian's answer is quite on point, and should solve any issues pointed out by the OP.

For now, we do not have a medium for public discussions other than GitHub Issues. Feel free to open up an issue if you are facing a problem with Magma or if you want to contribute to its improvement.
