### ISSUE TITLE
Building targets only?

### ISSUE THREAD

**Issue by Minilulatsch** [HexHive/magma#34]
Is it possible to only build the targets, without Docker but directly on the local system? I tried with libpng and libtiff, by first executing fetch.sh and than build.sh, with the necessary flags set. But the result is a "undefined reference to `main'" error in both cases, so I guess I'm missing some important step?

**Comment by Minilulatsch** [comment]
I think I've found my issue. The fuzzing targets use the libFuzzer-style "LLVMFuzzerTestOneInput()" function to process the inputs, which is always called by the main() function of the current fuzzing engine. As the targets are not linked again a fuzzing engine when building them by directly executing build.sh, the main() function is obviously missing. So adding a main() function to the fuzzing target, which reads the input from STDIN and feeds it to LLVMFuzzerTestOneInput() (just like the fuzzing engines do) does the trick

**Comment by zhanggenex** [comment]
@Minilulatsch Hey
Did you succeed building the php target outside the docker?
