### ISSUE TITLE
Which release to use?

### ISSUE THREAD

**Issue by ackdav** [HexHive/magma#55]
Sorry about opening an issue that is really a usage question.

Your homepage under ["getting started"](https://hexhive.epfl.ch/magma/docs/getting-started.html) recommends to use v1.0.4. However, this repo already has release v1.1.0 since October.

What do you suggest we use? (since magma is computationally quite heavy, I wanted to ask first before spending all the ressource on the wrong version)

thx! Also please let me know if there's another place that is more suited for usage questions..

**Comment by hazimeh** [comment]
The webpage is supposed to be updated with every push to the gh-pages branch, but since releases are on separate branches, they don't trigger the update.
The latest release is indeed the one on the `v1.1` branch.
