### ISSUE TITLE
Update "Getting Started" document to follow the latest changes

### ISSUE THREAD

**Issue by exKAZUu** [HexHive/magma#57]
I'm not sure whether this location is correct for posting an issue about the documents.

The current "Getting Started" document (https://hexhive.epfl.ch/magma/docs/getting-started.html) includes the following statement:

> The collected Magma instrumentation can be found in name-timestamped files inside workdir/afl/libpng/libpng_read_fuzzer/0/monitor.

, but it seems obsolete. I think this should be `The collected Magma instrumentation can be found in name-timestamped files inside workdir/ar/afl/libpng/libpng_read_fuzzer/0/ball.tar` now.

Also `git clone --branch v1.0.4 https://github.com/HexHive/magma.git` should be `git clone --branch v1.1 https://github.com/HexHive/magma.git` now?

**Comment by exKAZUu** [comment]
Oops, I'm using `TIMEOUT=1m`, so is there just no result due to too short time?

**Comment by adrianherrera** [comment]
Hey,

Yeah, you are correct, the documentation should say `workdir/ar` (`ball.tar` will only exist if `NO_ARCHIVE` is left unset).

Please feel free to submit a PR, otherwise I'll get around to it (eventually 🙂)

**Comment by exKAZUu** [comment]
@adrianherrera Thanks for the quick response. I can submit a PR, but I'm not sure where I can do it. `docs` directory in this repo seems not to include the document. Could you tell me the place?

**Comment by adrianherrera** [comment]
Ah yes, the web docs are in the gh-pages branch

**Comment by exKAZUu** [comment]
oh, i see, thanks!
