### ISSUE TITLE
Automatically stopping docker campaigns after a bug is triggered

### ISSUE THREAD

**Issue by scanakci** [HexHive/magma#66]
Hi guys,

Is there a way to stop fuzzing campaigns if a specific bug is triggered? For instance, if JCH232 bug is triggered in an instance, I do not want to fuzz using that instance longer to save CPU time. If MAGMA does not have this feature and continues to fuzz until a predetermined fuzzing duration, can you point me any potential scripts that I need to look into for implementing this feature? I submit a bunch of jobs to a server (and pay) so automatically stopping campaigns will save some money + time.

Thanks

**Comment by hazimeh** [comment]
The magma/run.sh script is the entrypoint for Docker containers and is responsible for timing out.
You could rewrite the campaign launching logic to check the monitor output for a non-zero value in the JCH232_T column and terminate the campaign when that criterion is satisfied.
This mechanism does not currently exist in Magma, so you'd have to fiddle around a bit to make it work and pass the bug ID (JCH232) from captainrc into the magma/run.sh script

**Comment by scanakci** [comment]
okay, thank you!
