### ISSUE TITLE
No corpus in libsndfile

### ISSUE THREAD

**Issue by shao-hua-li** [HexHive/magma#78]
Hi there,

I found that there's no corpus in libsndfile. Is this on purpose? I'm not able to run afl on libsndfile without corpus, however.

Thanks.

**Comment by adrianherrera** [comment]
Hi Shaohua,

Thanks for pointing this out! The libsndfile target was recently added via an external contributor, and we should have done our due diligence to ensure seeds were provided 😅

I am currently organizing a suitable corpus. I'll commit soon.

~Adrian

**Comment by hazimeh** [comment]
Thank you for pointing out this oversight :)
I had scheduled an evaluation of this release, but the libsndfile campaigns were still pending execution, so that issue must have gone unnoticed (until the campaigns would have been scheduled and inevitably failed).
We'll look into this!

**Comment by adrianherrera** [comment]
I've pushed a corpus based on the libsndfile test suite to the dev branch.

It is based off of the libsndfile test suite (https://github.com/libsndfile/libsndfile/tree/master/tests), where I just commented-out the `unlink` function call and collected all of the generated test files (that are <= 1MB).

@hazimeh I'll make a PR for the v1.2 branch.

**Comment by adrianherrera** [comment]
PR made: https://github.com/HexHive/magma/pull/79
