### ISSUE TITLE
No fuzzer included. This is just for building an analysis target

### ISSUE THREAD

**Issue by yh570** [HexHive/magma#81]
Hi, I found the `run.sh` in `klee` in the latest magma only contains 
```
echo "No fuzzer included. This is just for building an analysis target."
exit 1
```
I modified it as below:
```
args="${ARGS/@@/"'$1'"}"
if [ -z "$args" ]; then
    args="'$1'"
fi

klee --libc=uclibc --posix-runtime "$OUT/$PROGRAM.bc" ${@:2} $args
```
 However, I still get the same error message `No fuzzer included. This is just for building an analysis target`, the whole error message from the log file in `./work/log/klee_libpng_libpng_read_fuzzer_0_container.log` is shown below:

```
[2021-07-17 19:28] Container for klee/libpng/libpng_read_fuzzer started in 5eed506edb6a
/magma/targets/libpng/corpus/libpng_read_fuzzer/not_kitty.png: exit_code 127^M
/magma/targets/libpng/corpus/libpng_read_fuzzer/not_kitty_alpha.png: exit_code 127^M
/magma/targets/libpng/corpus/libpng_read_fuzzer/not_kitty_gamma.png: exit_code 127^M
/magma/targets/libpng/corpus/libpng_read_fuzzer/not_kitty_icc.png: exit_code 127^M
Campaign launched at 2021-07-17 19:28^M
No fuzzer included. This is just for building an analysis target.^M
Campaign terminated at 2021-07-17 19:28^M
````
And the captainrc file is shown below:
```
WORKDIR=./workdir 
REPEAT=3
TIMEOUT=24h
POLL=5
FUZZERS=(klee)
afl_TARGETS=(libpng libtiff libxml2)
```

I tested AFL, which works fine. Would you please give me some suggestions about this error? Thank you.

**Comment by hazimeh** [comment]
This is intentional. KLEE support is not complete; we only added it to compile the targets to be run under KLEE.
Check out `runonce.sh` for an example of how to invoke the target with KLEE.
You may need to run an interactive docker container to be able to do that.
