### ISSUE TITLE
angora and parmesan failing builds

### ISSUE THREAD

**Issue by johwi801** [HexHive/magma#85]
Hi, i found some builds that fail. Angora fails for targets libsndfile, php, and openssl, while parmesan fails with libsndfile, and sqlite3. Building parmesan with target php seems to not finish or it takes a very long time. Other fuzzers seem to build with these targets. Providing build logs below. Error for libsndfile seem to be same issue for both targets (undefined reference in alsa_open).

[parmesan_php_build.log](https://github.com/HexHive/magma/files/6991335/parmesan_php_build.log) (canceled by user)
[parmesan_sqlite3_build.log](https://github.com/HexHive/magma/files/6991336/parmesan_sqlite3_build.log)
[angora_libsndfile_build.log](https://github.com/HexHive/magma/files/6991337/angora_libsndfile_build.log)
[angora_openssl_build.log](https://github.com/HexHive/magma/files/6991338/angora_openssl_build.log)
[angora_php_build.log](https://github.com/HexHive/magma/files/6991339/angora_php_build.log)
[parmesan_libsndfile_build.log](https://github.com/HexHive/magma/files/6991340/parmesan_libsndfile_build.log)

**Comment by adrianherrera** [comment]
Hey @johwi801, 

I'm slowly making my way through these broken builds and have fixed a few of them.

Just so I know where to focus, which branch are you using?

**Comment by johwi801** [comment]
I am using the v1.2 branch currently. 

I very much appreciate the help!

**Comment by adrianherrera** [comment]
Hi @johwi801,

I've fixed some of the targets (openssl and libsndfile) in the dev branch, but I haven't been able to fix the php issues yet. I think that the issue relates to the libcxx version and the (quite old) version of LLVM that Angora relies on (compared to the newer libstdc++ that Ubuntu has); see https://bugs.llvm.org/show_bug.cgi?id=43140. This may have to be fixed upstream with the Angora devs.

**Comment by adrianherrera** [comment]
So the PHP + Angora (and hence also ParmeSAN, which is built on top of Angora) issue is indeed an upstream issue, and is not Magma related. Please open an issue with the respective fuzzer developers.

This only leaves the sqlite3 + ParmeSAN issue to investigate.

**Comment by adrianherrera** [comment]
Hi @johwi801,

The ParmeSAN errors on sqlite3 are upstream issues. I suggest you open an issue with the ParmeSAN developers.

I will close this issue now and merge in the `dev` updates into the `v1.2` branch.

**Comment by johwi801** [comment]
Ok thank you very much for the fixes!
