### ISSUE TITLE
Parmesan libpng: thread 'main' panicked at 'Could not read cfg targets file ...'

### ISSUE THREAD

**Issue by johwi801** [HexHive/magma#86]
When starting parmesan for target libpng the campaign terminates immediately and I get the following error:

```
[2021-08-16 16:59] Container for parmesan/libpng/libpng_read_fuzzer started in 147b41eb0169
Campaign launched at 2021-08-16 14:59
thread 'main' panicked at 'Could not read cfg targets file: Custom { kind: InvalidData, error: Error("invalid digit found in string", line: 5, column: 1) }', fuzzer/src/fuzz_main.rs:42:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Campaign terminated at 2021-08-16 14:59
```

**Comment by adrianherrera** [comment]
Hi @johwi801,

Are you able to provide more information? What exactly is the "invalid digit found in string"?

More information would help me diagnose the issue.

**Comment by adrianherrera** [comment]
Hi, I had a look at the JSON output. My guess is that it is failing because one of the callsite dominators is a negative value (`-1088809728`).

You will have to report this issue to the ParmeSAN developers.
