### ISSUE TITLE
A may-be incorrect patch file of libpng

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [HexHive/magma#90]
Hi!

Thanks for your great efforts of bringing Magam benchmark. 

I am playing with the benchmark and try to do some hack. I noticed the following code.

https://github.com/HexHive/magma/blob/4652a9c59284e8141fcd2801ec81e4262401678e/targets/libpng/patches/bugs/PNG005.patch#L24

I suppose it should be 
```c
 #ifdef MAGMA_ENABLE_CANARIES 
```

I am not sure whether I completely understand the meaning of `MAGMA_ENABLE_CANARIES`. But if I simply define a macro named as MAGMA_ENABLE_CANARIES, the compilation would fail. Please kindly correct if I am wrong.

Thanks for your help in advance.

**Comment by adrianherrera** [comment]
Good pickup! This is now fixed.
