### ISSUE TITLE
Why put in a docker?

### ISSUE THREAD

**Issue by zhanggenex** [HexHive/magma#92]
I am pretty curious of **why put all the fuzzers and targets and fuzzing campaign inside a docker**???

Imagine Jack is a skilled practioner in fuzzing. He already has all the settings and configurations (e.g., AFL, clang, ...) installed on his own computer.

One day he **has to** use this MAGMA data set. (Maybe suggested by reviewers from a top conference:-).) But all the fuzzers and targets are going to be reinstalled in a docker. If Jack is in China, the connection or git clone operation to GitHub is always unconnected these days. Sadly, Jack has no way to run this data set if the fuzzer and targets cannot be cloned into the docker.

I strongly suggest just give Jack the patched target source code. People who want to use this data set 100% have all the fuzzers and pre-settings installed on their own computer. **Only the targets inserted with bugs are what Jack needs**. And last but not least, don't try to push people to redo all the things inside a docker. It's really a waste of time for a skilled fuzzing practioner such as Jack. :-)

**Comment by zhanggenex** [comment]
国内的用户，如果要用这个数据集的话，请把docker里面github以及ubuntu apt源都换成国内的镜像，速度起飞

用原有的链接等到爸妈都不认识。。。。

**Comment by adrianherrera** [comment]
Hi,

I guess the original intention of using Docker was to make things as "reproducible" as possible (Ahmad, the original author, will be able to correct me if this is not the case).

I feel your pain; it can be quite frustrating (as a Magma user/developer) to tweak some fuzzer changes, and wait for the Docker build process to (fail to) build, and continually iterate over this cycle. Unfortunately, I don't really have time to look at this now. Of course, we are always welcome to PRs :)

If all you are after is the patched source code (can you please confirm), there might be an easy way to run those scripts outside of a Docker container. Let me have a look later today/tonight and get back to you (feel free to ping me if you don't!)

**Comment by zhanggenex** [comment]
@adrianherrera Thanks for your reply, I guess only the patched source code is not enough to conduct the experiments. I already used this data set for about 2 days and still working on my experiments. The whole evaluation must be running on the docker to get the desired results. So maybe only the patched source code is not a good solution.

I already figured out how to speed up the process in China by replacing the github and ubuntu apt urls with a mirror url.

Maybe I could submit a PR about this problem when I finished my experiments. :-)

Thanks

**Comment by zhanggenex** [comment]
Solved how to build magma locally in issue #93.

**Comment by blu3sh0rk** [comment]
> 国内的用户，如果要用这个数据集的话，请把docker里面github以及ubuntu apt源都换成国内的镜像，速度起飞
> 
> 用原有的链接等到爸妈都不认识。。。。

大佬，麻烦问下容器内源怎么改，我改了还是显示
apt-get update
Err:1 http://mirrors.163.com/debian stretch InRelease                         
  Temporary failure resolving 'mirrors.163.com'
Err:2 http://archive.canonical.com/ubuntu xenial InRelease                    
  Temporary failure resolving 'archive.canonical.com'
Err:3 http://mirrors.aliyun.com/ubuntu xenial InRelease                       
  Temporary failure resolving 'mirrors.aliyun.com'
Err:4 http://mirrors.163.com/debian stretch-updates InRelease        
  Temporary failure resolving 'mirrors.163.com'
Err:5 http://mirrors.aliyun.com/ubuntu xenial-updates InRelease      
  Temporary failure resolving 'mirrors.aliyun.com'
Err:6 http://mirrors.aliyun.com/ubuntu xenial-backports InRelease    
  Temporary failure resolving 'mirrors.aliyun.com'
Err:7 http://mirrors.163.com/debian stretch-backports InRelease      
  Temporary failure resolving 'mirrors.163.com'
0% [Connecting to mirrors.aliyun.com] [Connecting to mirrors.163.com]

**Comment by zhanggenex** [comment]
我是将sources.list放在./magma/里面，然后修改magma/preinstall.sh
添加一行
mv /magma/magma/sources.list /etc/apt/




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "HexHive/magma"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sun, Nov 7, 2021 11:06 PM
***@***.***&gt;;
Cc:&nbsp;"Gen ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [HexHive/magma] Why put in a docker? (Issue #92)





  
国内的用户，如果要用这个数据集的话，请把docker里面github以及ubuntu apt源都换成国内的镜像，速度起飞
 
用原有的链接等到爸妈都不认识。。。。
  
大佬，麻烦问下容器内源怎么改，我改了还是显示
 apt-get update
 Err:1 http://mirrors.163.com/debian stretch InRelease
 Temporary failure resolving 'mirrors.163.com'
 Err:2 http://archive.canonical.com/ubuntu xenial InRelease
 Temporary failure resolving 'archive.canonical.com'
 Err:3 http://mirrors.aliyun.com/ubuntu xenial InRelease
 Temporary failure resolving 'mirrors.aliyun.com'
 Err:4 http://mirrors.163.com/debian stretch-updates InRelease
 Temporary failure resolving 'mirrors.163.com'
 Err:5 http://mirrors.aliyun.com/ubuntu xenial-updates InRelease
 Temporary failure resolving 'mirrors.aliyun.com'
 Err:6 http://mirrors.aliyun.com/ubuntu xenial-backports InRelease
 Temporary failure resolving 'mirrors.aliyun.com'
 Err:7 http://mirrors.163.com/debian stretch-backports InRelease
 Temporary failure resolving 'mirrors.163.com'
 0% [Connecting to mirrors.aliyun.com] [Connecting to mirrors.163.com]
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by blu3sh0rk** [comment]
@

> 我是将sources.list放在./magma/里面，然后修改magma/preinstall.sh 添加一行 mv /magma/magma/sources.list /etc/apt/
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: "HexHive/magma" ***@***.***&gt;; Date:&nbsp;Sun, Nov 7, 2021 11:06 PM ***@***.***&gt;; Cc:&nbsp;"Gen ***@***.******@***.***&gt;; Subject:&nbsp;Re: [HexHive/magma] Why put in a docker? (Issue #92) 国内的用户，如果要用这个数据集的话，请把docker里面github以及ubuntu apt源都换成国内的镜像，速度起飞 用原有的链接等到爸妈都不认识。。。。 大佬，麻烦问下容器内源怎么改，我改了还是显示 apt-get update Err:1 http://mirrors.163.com/debian stretch InRelease Temporary failure resolving 'mirrors.163.com' Err:2 http://archive.canonical.com/ubuntu xenial InRelease Temporary failure resolving 'archive.canonical.com' Err:3 http://mirrors.aliyun.com/ubuntu xenial InRelease Temporary failure resolving 'mirrors.aliyun.com' Err:4 http://mirrors.163.com/debian stretch-updates InRelease Temporary failure resolving 'mirrors.163.com' Err:5 http://mirrors.aliyun.com/ubuntu xenial-updates InRelease Temporary failure resolving 'mirrors.aliyun.com' Err:6 http://mirrors.aliyun.com/ubuntu xenial-backports InRelease Temporary failure resolving 'mirrors.aliyun.com' Err:7 http://mirrors.163.com/debian stretch-backports InRelease Temporary failure resolving 'mirrors.163.com' 0% [Connecting to mirrors.aliyun.com] [Connecting to mirrors.163.com] — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

请问大佬，可以看看你的captainc 还有magma/preinstall.sh文件名 最近在服务器配这个测试集，挺多问题的
![image](https://user-images.githubusercontent.com/49183837/141675248-d9dd36db-b27a-49c5-a25c-b95c0f445b0f.png)

**Comment by hazimeh** [comment]
I'm closing this, given the workflow provided in #143.
