### ISSUE TITLE
Missing main() in sapi/fuzzer/fuzzer-exif.c, etc?

### ISSUE THREAD

**Issue by zhanggenex** [HexHive/magma#93]
@adrianherrera
Hi, Adrian, my own fuzzer cannot be running in the MAGMA docker.

I have to run my fuzzer outside the docker, so I need to compile the targets outside the docker.

All the targets succeeded except the php.

I can see the cause of failure is that there is no main() in sapi/fuzzer/fuzzer-exif.c, sapi/fuzzer/fuzzer-parser, etc.

I added
```
int main()
{
    return 0;
}
```
to these files, they can be compiled successfully.

But this compiled binary cannot run in the fuzzer.

Any tutorials to write the main() function or am I missing some steps in compiling the targets outside the docker?

Thanks!

**Comment by zhanggenex** [comment]
I checked the successfully compiled targets.

I think there must be some errors in the Makefile of php. The targets should be linked to the afl_driver.o when compiling. But it is missing.

Could anyone look into this?

Thanks!

**Comment by zhanggenex** [comment]
Finally, I figured out how to build all the targets outside the docker on my computer locally.

If you are interested, please take a look at my [tutorial](https://zhuanlan.zhihu.com/p/430280845).

**Comment by adrianherrera** [comment]
Great! I will have a read of your tutorial and see what we can incorporate into the codebase.
