### ISSUE TITLE
Building docker always fails

### ISSUE THREAD

**Issue by CourageCheng** [HexHive/magma#94]
Hello, I use magma in my Ubuntu docker, but when I run it  ./run. sh, it always reports an error. The error is as follows:
error creating aufs mount to /var/lib/docker/aufs/mnt/f5ad5933593199ad2758075710eca3df75a5f59ed866c684bf95e82d9f8980a9-init: mount target=/var/lib/docker/aufs/mnt/f5ad5933593199ad2758075710eca3df75a5f59ed866c684bf95e82d9f8980a9-init data=br:/var/lib/docker/aufs/diff/f5ad5933593199ad2758075710eca3df75a5f59ed866c684bf95e82d9f8980a9-init=rw:/var/lib/docker/aufs/diff/153a85559fa6281add91df7718bc1d64036c5b28d14aab5cfdc1ddaf7479b38e=ro+wh,dio,xino=/dev/shm/aufs.xino: invalid argument

**Comment by adrianherrera** [comment]
This seems like a docker error; e.g., https://stackoverflow.com/questions/30984569/error-error-creating-aufs-mount-to-when-building-dockerfile
