### ISSUE TITLE
Hangs after building libpng.

### ISSUE THREAD

**Issue by magicbounce** [HexHive/magma#95]
[afl_libpng_build.log](https://github.com/HexHive/magma/files/7757121/afl_libpng_build.log)
Hello,
To my understanding, the Magma benchmark will move on to build its next campaign after completing the build for one campaign so it can work on multiple campaigns in parallel.  However, my benchmark never moves onto building the next campaign after finishing afl/libpng.  I've attached the log of a previous attempt showing that afl/libpng was successfully built and a screenshot of my current attempt showing when I started and the time the screenshot was taken at.
![image](https://user-images.githubusercontent.com/31807983/146975652-75c86276-5cb1-4aaa-a4be-95b77f7189ef.png)

**Comment by adrianherrera** [comment]
Hi @magicbounce,

If you just want to build the Docker containers, you can run the following within the captain directory

```terminal
TARGET=libpng FUZZER=afl ./build.sh
```

Is this what you are after? I'm not sure what you are expecting; the attached screenshot shows the start of the fuzzing campaign after the container is built. Depending on your system configuration (number of cores, etc.) and your captainrc file, it might not be possible to run multiple builds in parallel.

**Comment by magicbounce** [comment]
changing the timeout on my captainrc from 24h to 30m helped.  seems like my virtual machine can't run multiple builds in parallel.  thank you!

**Comment by adrianherrera** [comment]
No problem, glad you got it sorted :)
