### ISSUE TITLE
Compiling each applications separately 

### ISSUE THREAD

**Issue by bernardnongpoh** [HexHive/magma#96]
Hi, I would like to compile Magma applications separately without requiring them to run in the docker. I wanted to have just simple plain applications but with bugs in them. Can we do that?

**Comment by LucasLeeNDS** [comment]
URL：https://zhuanlan.zhihu.com/p/430280845?utm_source=wechat_timeline&utm_medium=social&utm_oi=671347818648834048&utm_content=group3_article&utm_campaign=shareopn&s_r=0

**Comment by blu3sh0rk** [comment]
> Hi, I would like to compile Magma applications separately without requiring them to run in the docker. I wanted to have just simple plain applications but with bugs in them. Can we do that?

URL：https://zhuanlan.zhihu.com/p/430280845?utm_source=wechat_timeline&utm_medium=social&utm_oi=671347818648834048&utm_content=group3_article&utm_campaign=shareopn&s_r=0

**Comment by bernardnongpoh** [comment]
Cool. Thanks

**Comment by wideglide** [comment]
FYI - I do this in CI here: https://gitlab.com/fuzzing/magma

**Comment by bernardnongpoh** [comment]
Thanks
